name: Publish to ghcr.io

on:
  workflow_run:
    workflows: [Package with Maven]
    types: [completed]
    branches: [main]
 
 jobs:
  publish:
    runs-on: ubuntu-latest
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to the container registry
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
